### ISSUE TITLE
zone2global (or possibly go-junos) doesn't work against vSRX

### ISSUE THREAD

**Issue by dfex** [scottdware/zone2global#1]
```
./zone2global -srx 192.168.56.101 -u admin -p admin123
This device doesn't look to be an SRX (FIREFLY-PERIMETER). You can only run this script against an SRX.
```

Tested against vSRX/Firefly 12.1X47-D20.7

**Comment by scottdware** [comment]
Thanks for catching this. I'll make the adjustments and release an update later today.

**Comment by scottdware** [comment]
Fixed the issue. Updated the go-junos library to reflect the vSRX. I tested this against 12.1X47-D20.7 and 15.1X49-D15.4.

You'll have to re-download the binaries.
